# fly.toml app configuration file generated for product-sync on 2023-05-24T18:03:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "product-sync"
primary_region = "sea"

[env]
  HOST = "https://product-sync.fly.dev"
  PORT = "8081"
  SCOPES = "write_inventory,write_products"
  SHOPIFY_API_KEY = "fc3baf2cc5d3336e0b26b49c5862dc4e"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
